title: Omowumi Anthony
logo: Data.jpg
description: I am an Experienced Data Analyst skilled in extracting meaningful insights to solve real-world problems in business and society. I work with SQL, SSIS, Python, R, Power BI, and Advanced Excel with VBA to analyze large datasets, build dashboards, and automate data processes. My focus is on using data-driven solutions to drive impact and meaningful change
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
