title: Omowumi Anthony
logo: download.jpeg
description: A collection of my awesome projects.
show_downloads: false
#google_analytics: # (Optional) Add your GA tracking ID here if you have one
theme: jekyll-theme-cayman

# (Optional) Add social media links
#github:
 # owner_url: https://github.com/your-username
 # repository_url: https://github.com/your-username/your-repo-name

# (Optional) Set a logo if you want

